name: fastgc

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy>=1.22,<2.0
  - scipy>=1.9,<1.14
  - rasterio>=1.3
  - fiona>=1.9
  - shapely>=2.0
  - tqdm>=4.64
  - joblib>=1.3
  - psutil>=5.9
  - pip
  - pip:
      - laspy>=2.4
      - lazrs>=0.6