from pathlib import Path

import pytest

from fastgc.core import run_fastgc


def test_run_fastgc_missing_input_file():
    missing = Path("this_file_does_not_exist.las")

    with pytest.raises(FileNotFoundError):
        run_fastgc(
            in_path=str(missing),
            out_dir=None,
            sensor_mode="ALS",
            workflow="tile-run",
            products=["FAST_GC"],
            recursive=False,
            skip_existing=False,
            overwrite=False,
            grid_res=0.25,
            dem_method="min",
            dsm_method="max",
            chm_method="p2r",
            chm_methods=None,
            chm_surface_method="p2r",
            chm_smooth_method="none",
            chm_percentile=99.0,
            chm_percentile_low=None,
            chm_percentile_high=None,
            chm_pitfree_thresholds=None,
            chm_use_first_returns=False,
            chm_spikefree_freeze_distance=None,
            chm_spikefree_insertion_buffer=None,
            chm_median_size=3,
            chm_gaussian_sigma=1.0,
            chm_min_height=0.0,
            chm_fill_ground_voids_zero=True,
            chm_void_ground_threshold=0.15,
            terrain_products=["all"],
            hillshade_azimuth=315.0,
            hillshade_altitude=45.0,
            hillshade_z_factor=1.0,
            tpi_radius=3,
            twi_eps=1e-6,
            dtw_max_distance=None,
            change_input_type="FAST_DEM",
            change_mode="pairwise",
            change_threshold=0.0,
            change_baseline_index=0,
            change_source_subdir=None,
            change_sigma1=0.0,
            change_sigma2=0.0,
            change_lod_mode="threshold_only",
            itd_method="placeholder",
            itd_source_chm=None,
            tile_size_m=100.0,
            buffer_m=2.0,
            small_tile_merge_frac=0.25,
            cleanup_tiles=False,
            overwrite_tiles=False,
            apply_fp_fix=True,
            fp_fix_dem_res=0.25,
            fp_fix_nonground_to_ground_max_z=0.0,
            fp_fix_ground_to_nonground_min_z=0.06,
            keep_fp_fix_temp=False,
            n_jobs=1,
            joblib_backend="sequential",
            joblib_batch_size="auto",
            joblib_pre_dispatch="2*n_jobs",
        )


def test_run_fastgc_invalid_sensor_mode():
    missing = Path("this_file_does_not_exist.las")

    with pytest.raises(Exception):
        run_fastgc(
            in_path=str(missing),
            out_dir=None,
            sensor_mode="BAD_SENSOR",
            workflow="tile-run",
            products=["FAST_GC"],
            recursive=False,
            skip_existing=False,
            overwrite=False,
            grid_res=0.25,
            dem_method="min",
            dsm_method="max",
            chm_method="p2r",
            chm_methods=None,
            chm_surface_method="p2r",
            chm_smooth_method="none",
            chm_percentile=99.0,
            chm_percentile_low=None,
            chm_percentile_high=None,
            chm_pitfree_thresholds=None,
            chm_use_first_returns=False,
            chm_spikefree_freeze_distance=None,
            chm_spikefree_insertion_buffer=None,
            chm_median_size=3,
            chm_gaussian_sigma=1.0,
            chm_min_height=0.0,
            chm_fill_ground_voids_zero=True,
            chm_void_ground_threshold=0.15,
            terrain_products=["all"],
            hillshade_azimuth=315.0,
            hillshade_altitude=45.0,
            hillshade_z_factor=1.0,
            tpi_radius=3,
            twi_eps=1e-6,
            dtw_max_distance=None,
            change_input_type="FAST_DEM",
            change_mode="pairwise",
            change_threshold=0.0,
            change_baseline_index=0,
            change_source_subdir=None,
            change_sigma1=0.0,
            change_sigma2=0.0,
            change_lod_mode="threshold_only",
            itd_method="placeholder",
            itd_source_chm=None,
            tile_size_m=100.0,
            buffer_m=2.0,
            small_tile_merge_frac=0.25,
            cleanup_tiles=False,
            overwrite_tiles=False,
            apply_fp_fix=True,
            fp_fix_dem_res=0.25,
            fp_fix_nonground_to_ground_max_z=0.0,
            fp_fix_ground_to_nonground_min_z=0.06,
            keep_fp_fix_temp=False,
            n_jobs=1,
            joblib_backend="sequential",
            joblib_batch_size="auto",
            joblib_pre_dispatch="2*n_jobs",
        )


def test_run_fastgc_invalid_workflow():
    missing = Path("this_file_does_not_exist.las")

    with pytest.raises(Exception):
        run_fastgc(
            in_path=str(missing),
            out_dir=None,
            sensor_mode="ALS",
            workflow="not-a-real-workflow",
            products=["FAST_GC"],
            recursive=False,
            skip_existing=False,
            overwrite=False,
            grid_res=0.25,
            dem_method="min",
            dsm_method="max",
            chm_method="p2r",
            chm_methods=None,
            chm_surface_method="p2r",
            chm_smooth_method="none",
            chm_percentile=99.0,
            chm_percentile_low=None,
            chm_percentile_high=None,
            chm_pitfree_thresholds=None,
            chm_use_first_returns=False,
            chm_spikefree_freeze_distance=None,
            chm_spikefree_insertion_buffer=None,
            chm_median_size=3,
            chm_gaussian_sigma=1.0,
            chm_min_height=0.0,
            chm_fill_ground_voids_zero=True,
            chm_void_ground_threshold=0.15,
            terrain_products=["all"],
            hillshade_azimuth=315.0,
            hillshade_altitude=45.0,
            hillshade_z_factor=1.0,
            tpi_radius=3,
            twi_eps=1e-6,
            dtw_max_distance=None,
            change_input_type="FAST_DEM",
            change_mode="pairwise",
            change_threshold=0.0,
            change_baseline_index=0,
            change_source_subdir=None,
            change_sigma1=0.0,
            change_sigma2=0.0,
            change_lod_mode="threshold_only",
            itd_method="placeholder",
            itd_source_chm=None,
            tile_size_m=100.0,
            buffer_m=2.0,
            small_tile_merge_frac=0.25,
            cleanup_tiles=False,
            overwrite_tiles=False,
            apply_fp_fix=True,
            fp_fix_dem_res=0.25,
            fp_fix_nonground_to_ground_max_z=0.0,
            fp_fix_ground_to_nonground_min_z=0.06,
            keep_fp_fix_temp=False,
            n_jobs=1,
            joblib_backend="sequential",
            joblib_batch_size="auto",
            joblib_pre_dispatch="2*n_jobs",
        )